import { jsx as _jsx } from "react/jsx-runtime";
import PartnerManagementPage from '@/components/PartnerManagement/PartnerManagementPage';
import { addAdminSeller, addAdminSellerAccount, addAdminSellerDept, addAdminSellerMenu, addAdminSellerRole, assignAdminSellerAccountRoles, changeAdminSellerRoleStatus, changeAdminSellerStatus, createAdminSellerDirectLogin, createAdminSellerAccountDirectLogin, forceLogoutAdminSellerAccountSessions, forceLogoutAdminSellerSessions, getAdminSeller, getAdminSellerAccounts, getAdminSellerAccountRoles, getAdminSellerAccountSessions, getAdminSellerDepts, getAdminSellerDeptTree, getAdminSellerDirectLoginTickets, getAdminSellerList, getAdminSellerMenu, getAdminSellerMenus, getAdminSellerMenuTree, getAdminSellerLoginLogs, getAdminSellerOperLogs, getAdminSellerRole, getAdminSellerRoleMenuTree, getAdminSellerRoles, getAdminSellerSessions, lockAdminSellerAccount, removeAdminSellerDept, removeAdminSellerMenu, removeAdminSellerRoles, resetAdminSellerAccountDefaultPassword, resetAdminSellerOwnerPassword, unlockAdminSellerAccount, updateAdminSeller, updateAdminSellerAccount, updateAdminSellerDept, updateAdminSellerMenu, updateAdminSellerRole, } from '@/services/seller/seller';
const sellerConfig = {
    moduleKey: 'seller',
    title: '卖家管理',
    label: '卖家',
    idField: 'sellerId',
    noField: 'sellerNo',
    codeField: 'sellerCode',
    nameField: 'sellerName',
    shortNameField: 'sellerShortName',
    typeField: 'sellerType',
    levelField: 'sellerLevel',
    ownerIdField: 'sellerId',
    accountIdField: 'sellerAccountId',
    balanceTitle: '分销账户余额',
    levelDictType: 'seller_level',
    listTemplate: 'standard',
    searchStorageKey: 'admin-seller-management',
    searchFieldCount: 8,
    accountPermissions: {
        list: 'seller:admin:account:list',
        add: 'seller:admin:account:add',
        edit: 'seller:admin:account:edit',
        lock: 'seller:admin:account:lock',
        resetPwd: 'seller:admin:account:resetPwd',
        roleQuery: 'seller:admin:account:role:query',
        roleEdit: 'seller:admin:account:role:edit',
    },
    services: {
        list: getAdminSellerList,
        get: getAdminSeller,
        add: addAdminSeller,
        update: updateAdminSeller,
        changeStatus: changeAdminSellerStatus,
        getAccounts: getAdminSellerAccounts,
        addAccount: addAdminSellerAccount,
        updateAccount: updateAdminSellerAccount,
        lockAccount: lockAdminSellerAccount,
        unlockAccount: unlockAdminSellerAccount,
        listDepts: getAdminSellerDepts,
        getDeptTree: getAdminSellerDeptTree,
        addDept: addAdminSellerDept,
        updateDept: updateAdminSellerDept,
        removeDept: removeAdminSellerDept,
        getMenuTree: getAdminSellerMenuTree,
        listMenus: getAdminSellerMenus,
        getMenu: getAdminSellerMenu,
        addMenu: addAdminSellerMenu,
        updateMenu: updateAdminSellerMenu,
        removeMenu: removeAdminSellerMenu,
        getRoleMenuTree: getAdminSellerRoleMenuTree,
        listRoles: getAdminSellerRoles,
        getRole: getAdminSellerRole,
        addRole: addAdminSellerRole,
        updateRole: updateAdminSellerRole,
        changeRoleStatus: changeAdminSellerRoleStatus,
        removeRoles: removeAdminSellerRoles,
        resetAccountDefaultPassword: resetAdminSellerAccountDefaultPassword,
        listSubjectSessions: getAdminSellerSessions,
        listAccountSessions: getAdminSellerAccountSessions,
        forceLogoutSubject: forceLogoutAdminSellerSessions,
        forceLogoutAccount: forceLogoutAdminSellerAccountSessions,
        getAccountRoles: getAdminSellerAccountRoles,
        assignAccountRoles: assignAdminSellerAccountRoles,
        resetOwnerPassword: resetAdminSellerOwnerPassword,
        directLogin: createAdminSellerDirectLogin,
        directLoginAccount: createAdminSellerAccountDirectLogin,
        listLoginLogs: getAdminSellerLoginLogs,
        listOperLogs: getAdminSellerOperLogs,
        listDirectLoginTickets: getAdminSellerDirectLoginTickets,
    },
};
export default function SellerPage() {
    return _jsx(PartnerManagementPage, { config: sellerConfig });
}
