import PartnerManagementPage, { type PartnerModuleConfig } from '@/components/PartnerManagement/PartnerManagementPage';
import {
  addAdminSeller,
  addAdminSellerAccount,
  addAdminSellerDept,
  addAdminSellerMenu,
  addAdminSellerRole,
  assignAdminSellerAccountRoles,
  changeAdminSellerRoleStatus,
  changeAdminSellerStatus,
  createAdminSellerDirectLogin,
  forceLogoutAdminSellerAccountSessions,
  forceLogoutAdminSellerSessions,
  getAdminSeller,
  getAdminSellerAccounts,
  getAdminSellerAccountRoles,
  getAdminSellerDepts,
  getAdminSellerDeptTree,
  getAdminSellerDirectLoginTickets,
  getAdminSellerList,
  getAdminSellerMenu,
  getAdminSellerMenus,
  getAdminSellerMenuTree,
  getAdminSellerLoginLogs,
  getAdminSellerOperLogs,
  getAdminSellerRole,
  getAdminSellerRoleMenuTree,
  getAdminSellerRoles,
  removeAdminSellerDept,
  removeAdminSellerMenu,
  removeAdminSellerRoles,
  resetAdminSellerAccountDefaultPassword,
  resetAdminSellerOwnerPassword,
  updateAdminSeller,
  updateAdminSellerAccount,
  updateAdminSellerDept,
  updateAdminSellerMenu,
  updateAdminSellerRole,
} from '@/services/seller/seller';

const sellerConfig: PartnerModuleConfig = {
  moduleKey: 'seller',
  title: '卖家管理',
  label: '卖家',
  idField: 'sellerId',
  noField: 'sellerNo',
  codeField: 'sellerCode',
  nameField: 'sellerName',
  shortNameField: 'sellerShortName',
  typeField: 'sellerType',
  levelField: 'sellerLevel',
  ownerIdField: 'sellerId',
  accountIdField: 'sellerAccountId',
  balanceTitle: '分销账户余额',
  levelDictType: 'seller_level',
  services: {
    list: getAdminSellerList,
    get: getAdminSeller,
    add: addAdminSeller,
    update: updateAdminSeller,
    changeStatus: changeAdminSellerStatus,
    getAccounts: getAdminSellerAccounts,
    addAccount: addAdminSellerAccount,
    updateAccount: updateAdminSellerAccount,
    listDepts: getAdminSellerDepts,
    getDeptTree: getAdminSellerDeptTree,
    addDept: addAdminSellerDept,
    updateDept: updateAdminSellerDept,
    removeDept: removeAdminSellerDept,
    getMenuTree: getAdminSellerMenuTree,
    listMenus: getAdminSellerMenus,
    getMenu: getAdminSellerMenu,
    addMenu: addAdminSellerMenu,
    updateMenu: updateAdminSellerMenu,
    removeMenu: removeAdminSellerMenu,
    getRoleMenuTree: getAdminSellerRoleMenuTree,
    listRoles: getAdminSellerRoles,
    getRole: getAdminSellerRole,
    addRole: addAdminSellerRole,
    updateRole: updateAdminSellerRole,
    changeRoleStatus: changeAdminSellerRoleStatus,
    removeRoles: removeAdminSellerRoles,
    resetAccountDefaultPassword: resetAdminSellerAccountDefaultPassword,
    forceLogoutSubject: forceLogoutAdminSellerSessions,
    forceLogoutAccount: forceLogoutAdminSellerAccountSessions,
    getAccountRoles: getAdminSellerAccountRoles,
    assignAccountRoles: assignAdminSellerAccountRoles,
    resetOwnerPassword: resetAdminSellerOwnerPassword,
    directLogin: createAdminSellerDirectLogin,
    listLoginLogs: getAdminSellerLoginLogs,
    listOperLogs: getAdminSellerOperLogs,
    listDirectLoginTickets: getAdminSellerDirectLoginTickets,
  },
};

export default function SellerPage() {
  return <PartnerManagementPage config={sellerConfig} />;
}
