import { jsx as _jsx } from "react/jsx-runtime";
import PartnerManagementPage from '@/components/PartnerManagement/PartnerManagementPage';
import { addAdminBuyer, addAdminBuyerAccount, addAdminBuyerDept, addAdminBuyerMenu, addAdminBuyerRole, assignAdminBuyerAccountRoles, changeAdminBuyerRoleStatus, changeAdminBuyerStatus, createAdminBuyerAccountDirectLogin, createAdminBuyerDirectLogin, forceLogoutAdminBuyerAccountSessions, forceLogoutAdminBuyerSessions, getAdminBuyer, getAdminBuyerAccounts, getAdminBuyerAccountRoles, getAdminBuyerAccountSessions, getAdminBuyerDepts, getAdminBuyerDeptTree, getAdminBuyerDirectLoginTickets, getAdminBuyerList, getAdminBuyerLoginLogs, getAdminBuyerMenu, getAdminBuyerMenus, getAdminBuyerMenuTree, getAdminBuyerOperLogs, getAdminBuyerRole, getAdminBuyerRoleMenuTree, getAdminBuyerRoles, getAdminBuyerSessions, lockAdminBuyerAccount, removeAdminBuyerDept, removeAdminBuyerMenu, removeAdminBuyerRoles, resetAdminBuyerAccountDefaultPassword, resetAdminBuyerOwnerPassword, unlockAdminBuyerAccount, updateAdminBuyer, updateAdminBuyerAccount, updateAdminBuyerDept, updateAdminBuyerMenu, updateAdminBuyerRole, } from '@/services/buyer/buyer';
const buyerConfig = {
    moduleKey: 'buyer',
    title: '买家管理',
    label: '买家',
    idField: 'buyerId',
    noField: 'buyerNo',
    codeField: 'buyerCode',
    nameField: 'buyerName',
    shortNameField: 'buyerShortName',
    typeField: 'buyerType',
    levelField: 'buyerLevel',
    ownerIdField: 'buyerId',
    accountIdField: 'buyerAccountId',
    balanceTitle: '账户余额',
    showRechargePlaceholder: true,
    levelDictType: 'buyer_level',
    listTemplate: 'standard',
    searchStorageKey: 'admin-buyer-management',
    searchFieldCount: 8,
    accountPermissions: {
        list: 'buyer:admin:account:list',
        add: 'buyer:admin:account:add',
        edit: 'buyer:admin:account:edit',
        resetPwd: 'buyer:admin:account:resetPwd',
        roleQuery: 'buyer:admin:account:role:query',
        roleEdit: 'buyer:admin:account:role:edit',
        lock: 'buyer:admin:account:lock',
    },
    services: {
        list: getAdminBuyerList,
        get: getAdminBuyer,
        add: addAdminBuyer,
        update: updateAdminBuyer,
        changeStatus: changeAdminBuyerStatus,
        getAccounts: getAdminBuyerAccounts,
        addAccount: addAdminBuyerAccount,
        updateAccount: updateAdminBuyerAccount,
        lockAccount: lockAdminBuyerAccount,
        unlockAccount: unlockAdminBuyerAccount,
        listDepts: getAdminBuyerDepts,
        getDeptTree: getAdminBuyerDeptTree,
        addDept: addAdminBuyerDept,
        updateDept: updateAdminBuyerDept,
        removeDept: removeAdminBuyerDept,
        getMenuTree: getAdminBuyerMenuTree,
        listMenus: getAdminBuyerMenus,
        getMenu: getAdminBuyerMenu,
        addMenu: addAdminBuyerMenu,
        updateMenu: updateAdminBuyerMenu,
        removeMenu: removeAdminBuyerMenu,
        getRoleMenuTree: getAdminBuyerRoleMenuTree,
        listRoles: getAdminBuyerRoles,
        getRole: getAdminBuyerRole,
        addRole: addAdminBuyerRole,
        updateRole: updateAdminBuyerRole,
        changeRoleStatus: changeAdminBuyerRoleStatus,
        removeRoles: removeAdminBuyerRoles,
        resetAccountDefaultPassword: resetAdminBuyerAccountDefaultPassword,
        listSubjectSessions: getAdminBuyerSessions,
        listAccountSessions: getAdminBuyerAccountSessions,
        forceLogoutSubject: forceLogoutAdminBuyerSessions,
        forceLogoutAccount: forceLogoutAdminBuyerAccountSessions,
        getAccountRoles: getAdminBuyerAccountRoles,
        assignAccountRoles: assignAdminBuyerAccountRoles,
        resetOwnerPassword: resetAdminBuyerOwnerPassword,
        directLogin: createAdminBuyerDirectLogin,
        directLoginAccount: createAdminBuyerAccountDirectLogin,
        listLoginLogs: getAdminBuyerLoginLogs,
        listOperLogs: getAdminBuyerOperLogs,
        listDirectLoginTickets: getAdminBuyerDirectLoginTickets,
    },
};
export default function BuyerPage() {
    return _jsx(PartnerManagementPage, { config: buyerConfig });
}
