import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Descriptions, Drawer, Image, Space, Tag, Typography } from 'antd';
import { approveStatusText, dangerousCargoText, dimensionText, displayNumber, displayPrice, displayText, joinText, jsonArrayCount, productTypeText, weightText, } from './constants';
import styles from './style.module.css';
function sourceTag(record) {
    if (!record) {
        return '-';
    }
    return (_jsxs(Space, { size: 4, wrap: true, children: [_jsx(Tag, { color: "blue", children: record.systemKindLabel || record.systemKind || '-' }), _jsx(Typography.Text, { children: record.masterWarehouseName || '-' }), _jsx(Typography.Text, { type: "secondary", children: record.connectionCode })] }));
}
export default function SourceProductDetailDrawer({ open, record, onClose, }) {
    return (_jsxs(Drawer, { size: 760, title: record?.masterSku || '来源商品详情', open: open, onClose: onClose, destroyOnHidden: true, children: [_jsxs("div", { className: styles.detailLayout, children: [_jsx("div", { className: styles.detailImageBox, children: record?.imageUrl ? (_jsx(Image, { src: record.imageUrl, className: styles.detailImage })) : (_jsx("div", { className: styles.emptyImage, children: "\u65E0\u56FE" })) }), _jsxs(Descriptions, { size: "small", column: 1, className: styles.detailSummary, children: [_jsx(Descriptions.Item, { label: "\u6765\u6E90", children: sourceTag(record) }), _jsx(Descriptions.Item, { label: "\u6765\u6E90 SKU", children: _jsx(Typography.Text, { copyable: true, children: displayText(record?.masterSku) }) }), _jsx(Descriptions.Item, { label: "\u5546\u54C1\u540D\u79F0", children: displayText(record?.masterProductName) }), _jsx(Descriptions.Item, { label: "\u522B\u540D", children: displayText(record?.productAliasName) }), _jsx(Descriptions.Item, { label: "\u63CF\u8FF0", children: _jsx(Typography.Paragraph, { className: styles.descriptionText, children: displayText(record?.productDescription) }) })] })] }), _jsxs(Descriptions, { title: "\u57FA\u7840\u4FE1\u606F", size: "small", column: 2, children: [_jsx(Descriptions.Item, { label: "\u4EA7\u54C1\u7C7B\u578B", children: record?.productType === undefined || record?.productType === null
                            ? '-'
                            : productTypeText[record.productType] || record.productType }), _jsx(Descriptions.Item, { label: "\u5BA1\u6838\u72B6\u6001", children: record?.approveStatus
                            ? approveStatusText[record.approveStatus] || record.approveStatus
                            : '-' }), _jsx(Descriptions.Item, { label: "\u540C\u6B65\u72B6\u6001", children: displayText(record?.status) }), _jsx(Descriptions.Item, { label: "\u914D\u5BF9\u72B6\u6001", children: record?.pairingStatus === 'PAIRED' ? '已配对' : '未配对' }), _jsx(Descriptions.Item, { label: "\u9996\u6B21\u53D1\u73B0", children: displayText(record?.firstSeenTime) }), _jsx(Descriptions.Item, { label: "\u540C\u6B65\u65F6\u95F4", children: displayText(record?.lastSeenTime) })] }), _jsxs(Descriptions, { title: "\u8BC6\u522B\u7801\u4E0E\u5206\u7C7B", size: "small", column: 2, children: [_jsx(Descriptions.Item, { label: "\u4E3B\u8BC6\u522B\u7801", children: displayText(record?.mainCode) }), _jsx(Descriptions.Item, { label: "FNSKU", children: displayText(record?.fnsku) }), _jsx(Descriptions.Item, { label: "\u5176\u4ED6\u6761\u7801", span: 2, children: displayText(record?.otherCode) }), _jsx(Descriptions.Item, { label: "\u5206\u7C7B", span: 2, children: joinText([record?.cat1Name, record?.cat2Name, record?.cat3Name]) })] }), _jsxs(Descriptions, { title: "\u5C3A\u5BF8\u91CD\u91CF", size: "small", column: 2, children: [_jsx(Descriptions.Item, { label: "\u4EA7\u54C1\u5C3A\u5BF8", children: dimensionText(record) }), _jsx(Descriptions.Item, { label: "\u4EA7\u54C1\u91CD\u91CF", children: weightText(record) }), _jsx(Descriptions.Item, { label: "\u82F1\u5236\u5C3A\u5BF8", children: record?.lengthBs || record?.widthBs || record?.heightBs
                            ? `${displayNumber(record.lengthBs)} x ${displayNumber(record.widthBs)} x ${displayNumber(record.heightBs)} in`
                            : '-' }), _jsx(Descriptions.Item, { label: "\u82F1\u5236\u91CD\u91CF", children: displayNumber(record?.weightBs, ' lb') }), _jsx(Descriptions.Item, { label: "WMS\u5C3A\u5BF8", children: record?.wmsLength || record?.wmsWidth || record?.wmsHeight
                            ? `${displayNumber(record.wmsLength)} x ${displayNumber(record.wmsWidth)} x ${displayNumber(record.wmsHeight)} cm`
                            : '-' }), _jsx(Descriptions.Item, { label: "WMS\u91CD\u91CF", children: displayNumber(record?.wmsWeight, ' kg') })] }), _jsxs(Descriptions, { title: "\u7533\u62A5\u4FE1\u606F", size: "small", column: 2, children: [_jsx(Descriptions.Item, { label: "\u7533\u62A5\u4E2D\u6587\u540D", children: displayText(record?.declareNameCn) }), _jsx(Descriptions.Item, { label: "\u7533\u62A5\u82F1\u6587\u540D", children: displayText(record?.declareNameEn) }), _jsx(Descriptions.Item, { label: "\u6D77\u5173\u7F16\u7801", children: displayText(record?.customhouseCode) }), _jsx(Descriptions.Item, { label: "\u7533\u62A5\u4EF7", children: displayPrice(record?.declarePrice, record?.currencyCode) }), _jsx(Descriptions.Item, { label: "\u539F\u4EA7\u56FD\u5BB6/\u5730\u533A", children: displayText(record?.countryOfOriginName) }), _jsx(Descriptions.Item, { label: "\u5371\u9669\u54C1", children: record?.dangerousCargo === undefined || record?.dangerousCargo === null
                            ? '-'
                            : dangerousCargoText[record.dangerousCargo] || record.dangerousCargo })] }), _jsxs(Descriptions, { title: "\u5546\u57CE\u914D\u5BF9", size: "small", column: 2, children: [_jsx(Descriptions.Item, { label: "\u5BA2\u6237", children: displayText(record?.customerName) }), _jsx(Descriptions.Item, { label: "\u7CFB\u7EDF SKU", children: displayText(record?.systemSku) }), _jsx(Descriptions.Item, { label: "\u7CFB\u7EDF\u5546\u54C1\u540D", span: 2, children: displayText(record?.systemSkuName) })] }), _jsxs(Descriptions, { title: "\u6765\u6E90\u5FEB\u7167", size: "small", column: 2, children: [_jsxs(Descriptions.Item, { label: "\u5E73\u53F0 SKU \u4FE1\u606F", children: [jsonArrayCount(record?.platformSkuInfoJson), " \u6761"] }), _jsxs(Descriptions.Item, { label: "\u5DF4\u897F\u7A0E\u52A1\u4FE1\u606F", children: [jsonArrayCount(record?.brazilTaxInfoJson), " \u6761"] }), _jsx(Descriptions.Item, { label: "\u5FEB\u7167 Hash", span: 2, children: _jsx(Typography.Text, { copyable: true, className: styles.hashText, children: displayText(record?.sourcePayloadHash) }) })] })] }));
}
