-- Source product library read model.
-- Confirmed scope: source product library list/detail and future source SKU group binding.
-- Source of truth remains upstream_system_sku_candidate / upstream_system_sku_pairing.

create table if not exists source_product_group (
  source_sku_group_key    varchar(96)   not null                 comment '稳定来源SKU组key',
  repository_scope        varchar(32)   not null                 comment '来源仓库范围：OFFICIAL_MASTER/THIRD_PARTY_MASTER',
  master_sku              varchar(128)  not null                 comment '来源SKU',
  master_product_name     varchar(255)  not null                 comment '来源商品名',
  system_kind             varchar(64)   not null default ''      comment '来源系统类型',
  source_connection_codes varchar(1000) not null default ''      comment '来源连接编号列表',
  source_warehouse_names  varchar(1000) not null default ''      comment '来源仓库名称列表',
  warehouse_count         int           not null default 0       comment '来源仓库数量',
  source_row_count        int           not null default 0       comment '来源明细行数量',
  pairing_status          varchar(32)   not null default 'UNASSIGNED' comment '配对状态',
  status                  varchar(16)   not null default 'ACTIVE' comment '同步状态',
  latest_update_time      datetime      not null                 comment '组内最新更新时间',
  search_text             text          not null                 comment '搜索文本',
  rebuild_time            datetime      not null                 comment '读模型构建时间',
  primary key (source_sku_group_key),
  key idx_source_product_group_sku (repository_scope, master_sku),
  key idx_source_product_group_list (repository_scope, latest_update_time, source_sku_group_key),
  key idx_source_product_group_status (repository_scope, status),
  key idx_source_product_group_pairing (repository_scope, pairing_status)
) engine=innodb comment='来源SKU组读模型';

create table if not exists source_product_dimension_group (
  source_dimension_group_key varchar(160)  not null                 comment '稳定来源SKU尺寸组key',
  source_sku_group_key       varchar(96)   not null                 comment '稳定来源SKU组key',
  repository_scope           varchar(32)   not null                 comment '来源仓库范围',
  system_kind                varchar(64)   not null default ''      comment '来源系统类型',
  source_connection_codes    varchar(1000) not null default ''      comment '来源连接编号列表',
  source_warehouse_names     varchar(1000) not null default ''      comment '来源仓库名称列表',
  master_warehouse_name      varchar(1000) not null default ''      comment '来源仓库名称展示',
  warehouse_count            int           not null default 0       comment '来源仓库数量',
  source_row_count           int           not null default 0       comment '来源明细行数量',
  master_sku                 varchar(128)  not null                 comment '来源SKU',
  master_product_name        varchar(255)  not null                 comment '来源商品名',
  product_alias_name         varchar(255)  default ''               comment '来源商品别名',
  approve_status             varchar(32)   default ''               comment '审核状态',
  product_type               int                                    comment '产品类型',
  product_description        text                                   comment '来源商品描述',
  image_url                  varchar(1000) default ''               comment '图片URL',
  main_code                  varchar(128)  default ''               comment '主条码',
  other_code                 varchar(1000) default ''               comment '其他条码',
  fnsku                      varchar(1000) default ''               comment 'FNSKU',
  country_of_origin_name     varchar(100)  default ''               comment '原产国家/地区',
  currency_code              varchar(16)   default ''               comment '币种code',
  customhouse_code           varchar(64)   default ''               comment '海关编码',
  dangerous_cargo            int                                    comment '危险品code',
  declare_name_cn            varchar(255)  default ''               comment '申报中文名',
  declare_name_en            varchar(255)  default ''               comment '申报英文名',
  declare_price              decimal(18,4)                          comment '申报价格',
  product_height             decimal(18,4)                          comment '客户高(cm)',
  product_height_bs          decimal(18,4)                          comment '客户英制高(in)',
  product_length             decimal(18,4)                          comment '客户长(cm)',
  product_length_bs          decimal(18,4)                          comment '客户英制长(in)',
  product_weight             decimal(18,4)                          comment '客户重量(kg)',
  product_weight_bs          decimal(18,4)                          comment '客户英制重量(lb)',
  product_width              decimal(18,4)                          comment '客户宽(cm)',
  product_width_bs           decimal(18,4)                          comment '客户英制宽(in)',
  wms_height                 decimal(18,4)                          comment 'WMS高(cm)',
  wms_height_bs              decimal(18,4)                          comment 'WMS英制高(in)',
  wms_length                 decimal(18,4)                          comment 'WMS长(cm)',
  wms_length_bs              decimal(18,4)                          comment 'WMS英制长(in)',
  wms_weight                 decimal(18,4)                          comment 'WMS重量(kg)',
  wms_weight_bs              decimal(18,4)                          comment 'WMS英制重量(lb)',
  wms_width                  decimal(18,4)                          comment 'WMS宽(cm)',
  wms_width_bs               decimal(18,4)                          comment 'WMS英制宽(in)',
  cat1_name                  varchar(100)  default ''               comment '一级分类',
  cat2_name                  varchar(100)  default ''               comment '二级分类',
  cat3_name                  varchar(100)  default ''               comment '三级分类',
  platform_sku_info_json     longtext                               comment '平台SKU信息JSON摘要',
  brazil_tax_info_json       longtext                               comment '巴西税务信息JSON摘要',
  source_payload_hash        varchar(64)   default ''               comment '来源产品快照hash',
  status                     varchar(16)   not null default 'ACTIVE' comment '同步状态',
  search_text                text          not null                 comment '搜索文本',
  sync_batch_id              varchar(64)   default ''               comment '最新同步批次',
  first_seen_time            datetime      not null                 comment '首次发现时间',
  last_seen_time             datetime      not null                 comment '最近发现时间',
  update_time                datetime      not null                 comment '最新更新时间',
  pairing_status             varchar(32)   not null default 'UNASSIGNED' comment '配对状态',
  sku_pairing_id             bigint(20)                             comment '配对ID摘要',
  system_sku                 varchar(1000) default ''               comment '系统SKU摘要',
  system_sku_name            varchar(1000) default ''               comment '系统商品名摘要',
  customer_name              varchar(1000) default ''               comment '客户名摘要',
  rebuild_time               datetime      not null                 comment '读模型构建时间',
  primary key (source_dimension_group_key),
  key idx_source_product_dimension_group_list (repository_scope, update_time, source_dimension_group_key),
  key idx_source_product_dimension_group_sku_group (source_sku_group_key),
  key idx_source_product_dimension_group_master_sku (repository_scope, master_sku),
  key idx_source_product_dimension_group_status (repository_scope, status),
  key idx_source_product_dimension_group_pairing (repository_scope, pairing_status),
  key idx_source_product_dimension_group_approve (repository_scope, approve_status)
) engine=innodb comment='来源SKU尺寸组读模型';

create table if not exists source_product_warehouse_detail (
  id                         bigint(20)    not null auto_increment comment '主键',
  source_sku_group_key       varchar(96)   not null                 comment '稳定来源SKU组key',
  source_dimension_group_key varchar(160)  not null                 comment '稳定来源SKU尺寸组key',
  repository_scope           varchar(32)   not null                 comment '来源仓库范围',
  connection_code            varchar(64)   not null                 comment '来源连接编号',
  master_warehouse_name      varchar(128)  not null default ''      comment '来源仓库名',
  system_kind                varchar(64)   not null default ''      comment '来源系统类型',
  master_sku                 varchar(128)  not null                 comment '来源SKU',
  master_product_name        varchar(255)  not null                 comment '来源商品名',
  product_height             decimal(18,4)                          comment '客户高(cm)',
  product_height_bs          decimal(18,4)                          comment '客户英制高(in)',
  product_length             decimal(18,4)                          comment '客户长(cm)',
  product_length_bs          decimal(18,4)                          comment '客户英制长(in)',
  product_weight             decimal(18,4)                          comment '客户重量(kg)',
  product_weight_bs          decimal(18,4)                          comment '客户英制重量(lb)',
  product_width              decimal(18,4)                          comment '客户宽(cm)',
  product_width_bs           decimal(18,4)                          comment '客户英制宽(in)',
  wms_height                 decimal(18,4)                          comment 'WMS高(cm)',
  wms_height_bs              decimal(18,4)                          comment 'WMS英制高(in)',
  wms_length                 decimal(18,4)                          comment 'WMS长(cm)',
  wms_length_bs              decimal(18,4)                          comment 'WMS英制长(in)',
  wms_weight                 decimal(18,4)                          comment 'WMS重量(kg)',
  wms_weight_bs              decimal(18,4)                          comment 'WMS英制重量(lb)',
  wms_width                  decimal(18,4)                          comment 'WMS宽(cm)',
  wms_width_bs               decimal(18,4)                          comment 'WMS英制宽(in)',
  status                     varchar(16)   not null default 'ACTIVE' comment '同步状态',
  pairing_status             varchar(32)   not null default 'UNASSIGNED' comment '配对状态',
  sku_pairing_id             bigint(20)                             comment '配对ID',
  system_sku                 varchar(128)  default ''               comment '系统SKU',
  system_sku_name            varchar(255)  default ''               comment '系统商品名',
  customer_name              varchar(200)  default ''               comment '客户名',
  source_payload_hash        varchar(64)   default ''               comment '来源产品快照hash',
  wms_payload_hash           varchar(64)   default ''               comment 'WMS尺寸快照hash',
  first_seen_time            datetime      not null                 comment '首次发现时间',
  last_seen_time             datetime      not null                 comment '最近发现时间',
  update_time                datetime      not null                 comment '更新时间',
  rebuild_time               datetime      not null                 comment '读模型构建时间',
  primary key (id),
  unique key uk_source_product_warehouse_row (repository_scope, connection_code, master_sku),
  key idx_source_product_warehouse_sku_group (source_sku_group_key),
  key idx_source_product_warehouse_dimension_group (source_dimension_group_key),
  key idx_source_product_warehouse_master_sku (repository_scope, master_sku),
  key idx_source_product_warehouse_connection (connection_code)
) engine=innodb comment='来源SKU仓库明细读模型';
